version: "3.9"
services:
  oracle:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 80:80
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
    volumes:
      - mariadb:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  mariadb: